baseURL = "/"
languageCode = "en-us"
title = "Rishabh Naik"
theme= "paper"
paginate = 3
DefaultContentLanguage = "en"
ignoreErrors = ["error-remote-getjson"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

  [sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
